### ISSUE TITLE
Possible to use v1 notification transactions for v3 payment codes?

### ISSUE THREAD

**Issue by craigraw** [OpenBitcoinPrivacyProject/rfc#13]
I'm not sure how I missed this on previous readings, but the change to notification outputs with a 1 of 3 bare multisig excludes the use of normal address-based indexes. This means wallets that depend on such indexes (for example wallets that depend on Bitcoin Core or Electrum servers) won't be able to monitor for v3 notification outputs. 

Given this, is it possible to use v1 OP_RETURN style notification transactions for v3 payment codes? My reading of OBPP-05 indicates not, but I'd like to be sure. If it's not possible, then wallets that can't monitor for notification outputs will need to stick with v1 P2PKH receiving addresses.

**Comment by justusranvier** [comment]
That is correct, OP_RETURN were phased out because they are limited to one per transaction and there are several cases where it is desirable to perform more than one notification per transaction.

V3 payment codes were designed with the capabilities of cfilter-based architectures in mind, although it turned out in the end that basic BIP-158 filters were too limiting for full functionality so we developed a new filter type specifically for this use case: https://github.com/OpenBitcoinPrivacyProject/rfc/blob/master/obpp-04.mediawiki

**Comment by craigraw** [comment]
Thanks for the quick response. Unfortunately I think it's going to be difficult to get current address-based index implementations (such as Electrs) to change to support v3 notification outputs, so I'm not sure how quickly v3 will get adopted. Not many wallets use BIP-158 - it has the significant (although understandable) drawback of not providing mempool transactions.

In any event, it's good to have clarity on this point.

**Comment by justusranvier** [comment]
I don't understand where the idea comes from that not handling the mempool is a downside of BIP-157, since using cfilters to query confirmed blocks in no way precludes using other techniques to query the mempool.

**Comment by craigraw** [comment]
Indeed, assuming there is no access to an Electrum server or Bitcoin Core RPC, it's possible to listen on the P2P network for incoming mempool transactions. But if the wallet is offline when a relevant transaction is broadcast, it will miss it and need to wait for the first confirmation to pick it up via a BIP-158 block filter. Wasabi works [this way](https://docs.wasabiwallet.io/FAQ/FAQ-UseWasabi.html#how-does-wasabi-know-of-incoming-transactions-to-the-mempool). There are also [a question](https://github.com/bitcoin/bitcoin/pull/20702#issuecomment-753480327) about performance using compact block filters, although I haven't looked into this deeply.  

But my point wasn't specifically about the pros and cons of using BIP-158 filters - rather, my concern is that wallets using other mechanisms to communicate with the Bitcoin network are unlikely to switch to BIP-158 (a major change), and thus unfortunately adopting v3 widely will be challenging. I'd be happy to be wrong about this!
